apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-roboshop
  resources:
    requests:
      storage: 5Gi