apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    demo: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: efs-dynamic