apiVersion: v1
kind: Pod
metadata:
  name: roboshop1-pod1
  namespace: roboshop1
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
  - name: container-2
    image: almalinux:8
    command: ["sleep", "300"]
   


