apiVersion: v1
kind: Pod
metadata:
  name: roboshop-env
  namespace: roboshop1
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: NAME
      value: "HARI KRISHNA"


