apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop1
  name: roboshop-lables
  labels:   
    # key: lable-1
    # value: "LABLE-1"
    key1: value1
    key2: value2

spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: NAME
      value: "HARI KRISHNA"


