apiVersion: v1
kind: Pod
metadata:
  name: roboshop-annotation
  namespace: roboshop1
  annotations:   
    jenkins.url: "https://jenkins.com"
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: NAME
      value: "HARI KRISHNA"

