apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  namespace: roboshop1
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
      envFrom:
      - configMapKeyRef:
        name: roboshop-configmap
# instad of giveing multiple keys use below syntax that make our code csharter and easyer