apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: roboshop1
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: roboshop-secrets
        

