apiVersion: v1
kind: Pod
metadata:
  name: roboshop-resource
  namespace: roboshop1
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:  
        cpu: "200m"
        memory: "120Mi"

