apiVersion: v1
kind: Pod
metadata:
  name: clusterip-pod
  namespace: roboshop1
  lables:
    project: roboshop
    tier: two-tier
    demo: service
spec:
  containers:
  - name: container-1
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: roboshop1
spec:
