apiVersion: v1
kind: Service
metadata:
  name: efs-static
spec:
  type: LoadBalancer
  selector:
    demo: efs-static
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port