apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    course: DevOps
    Trainer: "SivakumarReddy"
  annotations: 
    jenkinsURL: "Https://jenkins.io"
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80