apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    course: DevOps
    Trainer: "SivakumarReddy"
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    env:
    - name: DEMO GRRETING
      value: "hello from the environment"