apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  namespace: roboshop1
  labels:
    demo: nodeport-service
    project: roboshop-nodeport
spec:
  containers:
  - name: container-1  
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: roboshop1
spec:
  type: NodePort
  selector:
    demo: nodeport-service
    project: roboshop-nodeport
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port

