apiVersion: v1
kind: PersistentVolume 
metadata:
  name: demo
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0f0ac73a52013c6c2