apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  StorageClassName: "" # it is empty in static type 
  volumeName: demo-static-volume
  accessModes:
    - ReadWriteOnce # only for ebs
  resources:
    requests:
      storage: 5Gi