apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  storageClassName: "" 
  volumeName: demo-static-volume
  accessModes:
    - ReadWriteOnce # only for ebs
  resources:
    requests:
      storage: 5Gi


      