apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    demo: demo-label
spec:
  containers:
  - name: demo-container
    image: nginx
    volumeMounts: 
    - name: demo-vm
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1a
  volumes:
  - name: demo-vm
    persistentVolumeClaim: 
      claimName: demo-pvc


      