apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer-pod
  namespace: roboshop1
  labels:
    demo: loadbalancer-service
    project: roboshop-loadbalancer
spec:
  containers:
  - name: container-1  
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: roboshop1
spec:
  type: LoadBalancer
  selector:
    demo: loadbalancer-service
    project: roboshop-loadbalancer
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port

