apiVersion: v1  # mostly it is v1
kind: pod
metadata: # it is nothing but information
  name: hello-pod
  namespace: roboshop
spec:
  containers:       # list of containers
  - name: hello-pod
    image: nginx 
    ports:
    - containerport: 80
  